/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedBeneficiariesRouteImport } from './routes/_authenticated/beneficiaries'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedGoodsRouteImport } from './routes/_authenticated/goods'
import { Route as AuthenticatedMoneyRouteImport } from './routes/_authenticated/money'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBeneficiariesRoute =
  AuthenticatedBeneficiariesRouteImport.update({
    id: '/beneficiaries',
    path: '/beneficiaries',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGoodsRoute = AuthenticatedGoodsRouteImport.update({
  id: '/goods',
  path: '/goods',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMoneyRoute = AuthenticatedMoneyRouteImport.update({
  id: '/money',
  path: '/money',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/beneficiaries': typeof AuthenticatedBeneficiariesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/goods': typeof AuthenticatedGoodsRoute
  '/money': typeof AuthenticatedMoneyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/beneficiaries': typeof AuthenticatedBeneficiariesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/goods': typeof AuthenticatedGoodsRoute
  '/money': typeof AuthenticatedMoneyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/beneficiaries': typeof AuthenticatedBeneficiariesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/goods': typeof AuthenticatedGoodsRoute
  '/_authenticated/money': typeof AuthenticatedMoneyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/auth' | '/beneficiaries' | '/dashboard' | '/goods' | '/money'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/beneficiaries' | '/dashboard' | '/goods' | '/money'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/beneficiaries'
    | '/_authenticated/dashboard'
    | '/_authenticated/goods'
    | '/_authenticated/money'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/beneficiaries': {
      id: '/_authenticated/beneficiaries'
      path: '/beneficiaries'
      fullPath: '/beneficiaries'
      preLoaderRoute: typeof AuthenticatedBeneficiariesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/goods': {
      id: '/_authenticated/goods'
      path: '/goods'
      fullPath: '/goods'
      preLoaderRoute: typeof AuthenticatedGoodsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/money': {
      id: '/_authenticated/money'
      path: '/money'
      fullPath: '/money'
      preLoaderRoute: typeof AuthenticatedMoneyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBeneficiariesRoute: typeof AuthenticatedBeneficiariesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGoodsRoute: typeof AuthenticatedGoodsRoute
  AuthenticatedMoneyRoute: typeof AuthenticatedMoneyRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBeneficiariesRoute: AuthenticatedBeneficiariesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGoodsRoute: AuthenticatedGoodsRoute,
  AuthenticatedMoneyRoute: AuthenticatedMoneyRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
